### ISSUE TITLE
新api有头绪吗

### ISSUE THREAD

**Issue by mynuolr** [xfkencon/land-leg-PY#1]
我逆向apk，跟踪so到解密的地方，没有数据包给我对比

**Comment by xfkencon** [comment]
新的我只有个没什么用的日志文件。有个Algo-ID仿佛很有趣
[ty.txt](https://github.com/xfkencon/land-leg-PY/files/519868/ty.txt)

**Comment by mynuolr** [comment]
这样啊。~

**Comment by mynuolr** [comment]
调用So 解密出来的

**Comment by KaiYuan-Guo** [comment]
请各位查看下自己的邮箱。
